### PR TITLE
detain History

### PR DESCRIPTION
**Pull request by joegrip**
I added the detain history as per the issue. Not 100% sure it will work. Is there a way to test other than in production?

### CODE REVIEW

**Comment by ginglis13** [comment]
yea it's hard to test locally unfortunately. a workaround has been to just pass text directly into the function being worked on and see if the output matches what you expect. but it's kind of annoying haha

e: misclicked close my b

**Comment by joegrip** [comment]
Can I test without the secrets file?

**Comment by ginglis13** [comment]
Yes, i believe the 'secret' stuff needed for these functions isn't really necessary, you could just throw gibberish in there. 

Also, it might make sense to use JSON for storing history w just key name value number of times detained

**Comment by joegrip** [comment]
It's all tested and works using json
I imported json in detain.py and app.py. I had to do that in testing but not sure if needed for produciton

**Review by ginglis13 — COMMENTED** [review]
noice yo

**Pull request merged**
